# Generated by Django 3.0.6 on 2020-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='mobile',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
